version: '3.7'
services:
  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    ports:
      - "9000:9000"
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: volume
        source: portainer_data
        target: /data
    deploy:
      placement:
        constraints:
          - node.role == manager

  viz:
    image: dockersamples/visualizer
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    deploy:
      placement:
        constraints:
          - node.role == manager
  proxy:
    image: traefik 
    ports:
      - "80:80"
      - "9090:8080"
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    command: --docker --docker.swarmMode --docker.domain=test-service.com --docker.watch --api
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - proxy-net
  app1:
    image: cristopherpinzon/docker_exercise
    environment:
      - SECRET='Service 1 Env'
    deploy:
      labels:
        traefik.port: "3000"
      replicas: 4
      placement:
        constraints:
          - node.role == worker
    networks:
      - proxy-net
  
  app2:
    image: cristopherpinzon/docker_exercise
    environment:
      - SECRET='Service 2 Env'
    deploy:
      replicas: 4
      labels:
        traefik.port: "3000"
      placement:
        constraints:
          - node.role == worker
    networks:
      -  proxy-net

volumes:
  portainer_data:  

networks:
  proxy-net:
    driver: overlay