version: '3'
services:
  app1:
    image: cristopherpinzon/docker_exercise
    environment:
      - SECRET='Service 1 Env'
    ports:
      - "3000:3000"
  app2:
    image: cristopherpinzon/docker_exercise
    environment:
      - SECRET='Service 2 Env'
    ports:
      - "3001:3000"
